name: "[English] Feature Request"
description: "Create a report to help us improve"
title: "[Feature Request] "
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!

        NOTE: Be sure to put a clear and concise title **AFTER** `[Feature Request]` in the text box above.

        <!-- template -->
  - type: textarea
    id: "description"
    attributes:
      label: "Feature Description"
      description: |
        A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: "additional"
    attributes:
      label: "Additional"
      description: |
        Add any other context or screenshots about the feature request here.
